# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 872bd73f3201c919748ba5c2a029dd16706ae315b3153efcc104ef716e2d7ee52f2e111ae596d476c0189d50647f530a3b0cfeeedbe0df6dcdfddc420c01010a
  admin_email: user@example.com
  admin_password: changeme

test:
  secret_key_base: 98df2106ac4085267c9cfe96fb410bedc9435e2f1b8a15a3a04cc3ef83b367a2a8df88419e7917212ba5601c977af7e2d11b7b80459bf8e286354d9e9a4342fe
  admin_email: user@example.com
  admin_password: changeme

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_email:     <%= ENV['PFITMAP_ADMIN_EMAIL'] %>
  admin_password:  <%= ENV['PFITMAP_ADMIN_PASSWD'] %>
